### PR TITLE
Improve script to compare Debian and Elixir.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Is ther esomethign wrong with this patch blocking its inclusion?

**Comment by joncison** [comment]
apologies ... missed this the first time,  thanks!

**Comment by petterreinholdtsen** [comment]
Ah, good thing I asked.  With two so old pull requests, I was wondering if the project was dead.

**Comment by joncison** [comment]
Not dead ... @matuskalas I know is interested in pushing this.  All down to time.  Most likely, the integration of info. from Debian will probably be accomplished through the mooted new (GitHub-based) content management architecture for _bio.tools_ that's currently under discussion ... see https://github.com/bio-tools/content and https://github.com/bio-tools/content/issues (a longer-term project)

**Pull request merged**
